import type { CodingQuestion } from "@/data/types";

/**
 * GENERATED by scripts/seed-banks.mjs - do not edit by hand.
 *
 * One lazy chunk per lesson so a lesson page only downloads the coding
 * questions for the lesson being read.
 */
export const CODING_LOADERS: Record<string, () => Promise<CodingQuestion[]>> = {
  "intro/what-is-javascript": () => import("./intro/what-is-javascript.json").then((m) => m.default as CodingQuestion[]),
  "intro/why-javascript-for-automation": () => import("./intro/why-javascript-for-automation.json").then((m) => m.default as CodingQuestion[]),
  "intro/how-javascript-runs": () => import("./intro/how-javascript-runs.json").then((m) => m.default as CodingQuestion[]),
  "intro/setting-up-environment": () => import("./intro/setting-up-environment.json").then((m) => m.default as CodingQuestion[]),
  "basics/variables": () => import("./basics/variables.json").then((m) => m.default as CodingQuestion[]),
  "basics/data-types": () => import("./basics/data-types.json").then((m) => m.default as CodingQuestion[]),
  "basics/operators": () => import("./basics/operators.json").then((m) => m.default as CodingQuestion[]),
  "basics/type-conversions": () => import("./basics/type-conversions.json").then((m) => m.default as CodingQuestion[]),
  "control-flow/if-else": () => import("./control-flow/if-else.json").then((m) => m.default as CodingQuestion[]),
  "control-flow/switch-case": () => import("./control-flow/switch-case.json").then((m) => m.default as CodingQuestion[]),
  "control-flow/loops-iteration": () => import("./control-flow/loops-iteration.json").then((m) => m.default as CodingQuestion[]),
  "control-flow/loop-control": () => import("./control-flow/loop-control.json").then((m) => m.default as CodingQuestion[]),
  "strings/string-basics": () => import("./strings/string-basics.json").then((m) => m.default as CodingQuestion[]),
  "strings/string-methods": () => import("./strings/string-methods.json").then((m) => m.default as CodingQuestion[]),
  "strings/template-literals": () => import("./strings/template-literals.json").then((m) => m.default as CodingQuestion[]),
  "strings/string-performance": () => import("./strings/string-performance.json").then((m) => m.default as CodingQuestion[]),
  "functions/function-basics": () => import("./functions/function-basics.json").then((m) => m.default as CodingQuestion[]),
  "functions/arrow-functions": () => import("./functions/arrow-functions.json").then((m) => m.default as CodingQuestion[]),
  "functions/arguments-and-params": () => import("./functions/arguments-and-params.json").then((m) => m.default as CodingQuestion[]),
  "functions/lexical-scope-closures": () => import("./functions/lexical-scope-closures.json").then((m) => m.default as CodingQuestion[]),
  "functions/callbacks": () => import("./functions/callbacks.json").then((m) => m.default as CodingQuestion[]),
  "arrays/array-basics": () => import("./arrays/array-basics.json").then((m) => m.default as CodingQuestion[]),
  "arrays/array-methods": () => import("./arrays/array-methods.json").then((m) => m.default as CodingQuestion[]),
  "arrays/advanced-arrays": () => import("./arrays/advanced-arrays.json").then((m) => m.default as CodingQuestion[]),
  "arrays/reduce": () => import("./arrays/reduce.json").then((m) => m.default as CodingQuestion[]),
  "arrays/array-flattening": () => import("./arrays/array-flattening.json").then((m) => m.default as CodingQuestion[]),
  "objects/object-basics": () => import("./objects/object-basics.json").then((m) => m.default as CodingQuestion[]),
  "objects/object-methods": () => import("./objects/object-methods.json").then((m) => m.default as CodingQuestion[]),
  "objects/destructuring": () => import("./objects/destructuring.json").then((m) => m.default as CodingQuestion[]),
  "objects/optional-chaining-nullish": () => import("./objects/optional-chaining-nullish.json").then((m) => m.default as CodingQuestion[]),
  "objects/map-set": () => import("./objects/map-set.json").then((m) => m.default as CodingQuestion[]),
  "objects/arrays-of-objects": () => import("./objects/arrays-of-objects.json").then((m) => m.default as CodingQuestion[]),
  "async/async-basics": () => import("./async/async-basics.json").then((m) => m.default as CodingQuestion[]),
  "async/promises": () => import("./async/promises.json").then((m) => m.default as CodingQuestion[]),
  "async/promise-composition": () => import("./async/promise-composition.json").then((m) => m.default as CodingQuestion[]),
  "async/async-await": () => import("./async/async-await.json").then((m) => m.default as CodingQuestion[]),
  "async/fetch-apis": () => import("./async/fetch-apis.json").then((m) => m.default as CodingQuestion[]),
  "async/event-loop": () => import("./async/event-loop.json").then((m) => m.default as CodingQuestion[]),
  "classes/class-basics": () => import("./classes/class-basics.json").then((m) => m.default as CodingQuestion[]),
  "classes/class-inheritance": () => import("./classes/class-inheritance.json").then((m) => m.default as CodingQuestion[]),
  "classes/prototypal-inheritance": () => import("./classes/prototypal-inheritance.json").then((m) => m.default as CodingQuestion[]),
  "classes/composition-over-inheritance": () => import("./classes/composition-over-inheritance.json").then((m) => m.default as CodingQuestion[]),
  "classes/json": () => import("./classes/json.json").then((m) => m.default as CodingQuestion[]),
  "dom/dom-basics": () => import("./dom/dom-basics.json").then((m) => m.default as CodingQuestion[]),
  "dom/dom-selection": () => import("./dom/dom-selection.json").then((m) => m.default as CodingQuestion[]),
  "dom/dom-manipulation": () => import("./dom/dom-manipulation.json").then((m) => m.default as CodingQuestion[]),
  "dom/events": () => import("./dom/events.json").then((m) => m.default as CodingQuestion[]),
  "dom/forms": () => import("./dom/forms.json").then((m) => m.default as CodingQuestion[]),
  "dom/window-object": () => import("./dom/window-object.json").then((m) => m.default as CodingQuestion[]),
  "modules/modules": () => import("./modules/modules.json").then((m) => m.default as CodingQuestion[]),
  "modules/dynamic-imports": () => import("./modules/dynamic-imports.json").then((m) => m.default as CodingQuestion[]),
  "modules/package-managers": () => import("./modules/package-managers.json").then((m) => m.default as CodingQuestion[]),
  "modules/module-bundlers": () => import("./modules/module-bundlers.json").then((m) => m.default as CodingQuestion[]),
  "modules/ecmascript": () => import("./modules/ecmascript.json").then((m) => m.default as CodingQuestion[]),
  "scope-hoisting/scope-rules": () => import("./scope-hoisting/scope-rules.json").then((m) => m.default as CodingQuestion[]),
  "scope-hoisting/hoisting": () => import("./scope-hoisting/hoisting.json").then((m) => m.default as CodingQuestion[]),
  "scope-hoisting/tdz": () => import("./scope-hoisting/tdz.json").then((m) => m.default as CodingQuestion[]),
  "scope-hoisting/this-binding": () => import("./scope-hoisting/this-binding.json").then((m) => m.default as CodingQuestion[]),
  "error-handling/try-catch": () => import("./error-handling/try-catch.json").then((m) => m.default as CodingQuestion[]),
  "error-handling/error-types": () => import("./error-handling/error-types.json").then((m) => m.default as CodingQuestion[]),
  "error-handling/async-errors": () => import("./error-handling/async-errors.json").then((m) => m.default as CodingQuestion[]),
  "error-handling/debugging": () => import("./error-handling/debugging.json").then((m) => m.default as CodingQuestion[]),
  "iterators/iterator-protocol": () => import("./iterators/iterator-protocol.json").then((m) => m.default as CodingQuestion[]),
  "iterators/generators": () => import("./iterators/generators.json").then((m) => m.default as CodingQuestion[]),
  "iterators/custom-iterables": () => import("./iterators/custom-iterables.json").then((m) => m.default as CodingQuestion[]),
  "storage-apis/storage": () => import("./storage-apis/storage.json").then((m) => m.default as CodingQuestion[]),
  "storage-apis/cookies": () => import("./storage-apis/cookies.json").then((m) => m.default as CodingQuestion[]),
  "storage-apis/timers-intervals": () => import("./storage-apis/timers-intervals.json").then((m) => m.default as CodingQuestion[]),
  "testing/unit-testing": () => import("./testing/unit-testing.json").then((m) => m.default as CodingQuestion[]),
  "testing/test-doubles": () => import("./testing/test-doubles.json").then((m) => m.default as CodingQuestion[]),
  "testing/e2e-testing": () => import("./testing/e2e-testing.json").then((m) => m.default as CodingQuestion[]),
  "testing/test-data-patterns": () => import("./testing/test-data-patterns.json").then((m) => m.default as CodingQuestion[]),
  "performance-security/performance-basics": () => import("./performance-security/performance-basics.json").then((m) => m.default as CodingQuestion[]),
  "performance-security/browser-rendering": () => import("./performance-security/browser-rendering.json").then((m) => m.default as CodingQuestion[]),
  "performance-security/security": () => import("./performance-security/security.json").then((m) => m.default as CodingQuestion[]),
  "advanced/regex-intro": () => import("./advanced/regex-intro.json").then((m) => m.default as CodingQuestion[]),
  "advanced/legacy-var": () => import("./advanced/legacy-var.json").then((m) => m.default as CodingQuestion[]),
  "advanced/legacy-topics": () => import("./advanced/legacy-topics.json").then((m) => m.default as CodingQuestion[]),
  "advanced/interview-prep": () => import("./advanced/interview-prep.json").then((m) => m.default as CodingQuestion[]),
};

export function hasCodingBank(lessonKey: string): boolean {
  return lessonKey in CODING_LOADERS;
}

export async function getCodingQuestions(lessonKey: string): Promise<CodingQuestion[]> {
  const loader = CODING_LOADERS[lessonKey];
  if (!loader) return [];
  try {
    return await loader();
  } catch {
    return [];
  }
}
