// Seeds one JSON file per lesson for the practice and coding banks, then
// regenerates the lazy-load registry for each. Safe to re-run: existing
// questions are preserved.
//
// Run: node scripts/seed-banks.mjs
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

const { CURRICULUM } = await import(pathToFileURL(path.resolve("scripts/_curriculum.mjs")).href);

const TARGETS = [
  {
    dir: "src/data/javascript/questions",
    registry: "src/data/javascript/questions/registry.ts",
    type: "QAQuestion",
    header: `import type { QAQuestion } from "@/data/types";

/**
 * GENERATED by scripts/seed-banks.mjs - do not edit by hand.
 *
 * One lazy chunk per lesson so a lesson page only downloads the questions for
 * the lesson being read.
 */
export const PRACTICE_LOADERS: Record<string, () => Promise<QAQuestion[]>> = {`,
    footer: `};

export function hasPracticeBank(lessonKey: string): boolean {
  return lessonKey in PRACTICE_LOADERS;
}

export async function getPracticeQuestions(lessonKey: string): Promise<QAQuestion[]> {
  const loader = PRACTICE_LOADERS[lessonKey];
  if (!loader) return [];
  try {
    return await loader();
  } catch {
    return [];
  }
}`,
  },
  {
    dir: "src/data/javascript/coding",
    registry: "src/data/javascript/coding/registry.ts",
    type: "CodingQuestion",
    header: `import type { CodingQuestion } from "@/data/types";

/**
 * GENERATED by scripts/seed-banks.mjs - do not edit by hand.
 *
 * One lazy chunk per lesson so a lesson page only downloads the coding
 * questions for the lesson being read.
 */
export const CODING_LOADERS: Record<string, () => Promise<CodingQuestion[]>> = {`,
    footer: `};

export function hasCodingBank(lessonKey: string): boolean {
  return lessonKey in CODING_LOADERS;
}

export async function getCodingQuestions(lessonKey: string): Promise<CodingQuestion[]> {
  const loader = CODING_LOADERS[lessonKey];
  if (!loader) return [];
  try {
    return await loader();
  } catch {
    return [];
  }
}`,
  },
];

for (const { dir, registry, type, header, footer } of TARGETS) {
  const entries = [];
  const rows = [];

  for (const topic of CURRICULUM) {
    fs.mkdirSync(path.join(dir, topic.slug), { recursive: true });
    let seeded = 0;
    let total = 0;

    for (const lesson of topic.lessons) {
      const file = path.join(dir, topic.slug, `${lesson.slug}.json`);
      let qs = [];
      if (fs.existsSync(file)) {
        try {
          qs = JSON.parse(fs.readFileSync(file, "utf8"));
          if (!Array.isArray(qs)) qs = [];
        } catch (e) {
          console.warn(`  !! ${file} invalid, reseeding: ${e.message}`);
          qs = [];
        }
      }
      qs = qs
        .map((q, i) => ({ ...q, id: typeof q.id === "number" ? q.id : i + 1 }))
        .filter((q) => q && typeof q.question === "string" && typeof q.answer === "string");
      if (!qs.length) seeded++;
      total += qs.length;
      fs.writeFileSync(file, JSON.stringify(qs, null, 2) + "\n");
      entries.push(
        `  ${JSON.stringify(`${topic.slug}/${lesson.slug}`)}: () => import("./${topic.slug}/${lesson.slug}.json").then((m) => m.default as ${type}[]),`
      );
    }

    const n = topic.lessons.length;
    rows.push(
      `  ${topic.slug.padEnd(22)} lessons=${String(n).padStart(2)} seeded=${seeded} questions=${String(total).padStart(4)}`
    );
  }

  fs.writeFileSync(registry, `${header}\n${entries.join("\n")}\n${footer}\n`);
  console.log(`${dir}\n${rows.join("\n")}\n  -> ${registry}\n`);
}
